### ISSUE TITLE
"Learn More. Some connected experiences aren't available" warning EVERY SINGLE PAGE of OneNote Mac

### ISSUE THREAD

**Issue by ellenble** [MicrosoftDocs/OfficeDocs-DeployOffice#487] opened 2019-11-14 05:00 UTC
Please turn it off or make it pop up JUST ONCE or as a notification, NOT at the top of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd465474-5237-e58f-c3a8-a52f0c6f0afa
* Version Independent ID: fa4d9d36-c115-4044-0ede-90629e193b83
* Content: [Required service data for Office](https://docs.microsoft.com/en-us/deployoffice/privacy/required-service-data)
* Content Source: [DeployOffice/privacy/required-service-data.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/required-service-data.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by ItzLevvie** [comment] 2019-11-14 09:33
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/486

**Closed** 2019-11-14 17:10 UTC
