### ISSUE TITLE
Install Proofing tool Office 2019

### ISSUE THREAD

**Issue by alexverschoor** [MicrosoftDocs/OfficeDocs-DeployOffice#166] opened 2018-10-30 14:12 UTC
Installed Office 2019 without issue, but I can't get the Proofing install to work.

Error message:
_"We can't install

This product can't be installed on the selected update channel. Please contact your system administrator and try again."_

Below the XML for Office:

<Configuration>
  <Add OfficeClientEdition="64" Channel="PerpetualVL2019">
    <Product ID="ProPlus2019Volume">
      <Language ID="en-us" />
    </Product>
    <Product ID="VisioPro2019Volume">
      <Language ID="en-us" />
    </Product>
    <Product ID="ProjectPro2019Volume">
      <Language ID="en-us" />
    </Product>
  </Add>

  
  
  
</Configuration>

And here the XML for Proofing:

<Configuration>
  <Add OfficeClientEdition="64" Channel="PerpetualVL2019">
	<Product ID="ProofingTools">
        <Language ID="nl-nl" />
    </Product>
  </Add>

  
  
  
</Configuration>

**Comment by alexverschoor** [comment] 2018-10-30 14:13
Office XML (removed  < and >):

Configuration
  Add OfficeClientEdition="64" Channel="PerpetualVL2019"
    Product ID="ProPlus2019Volume"
      Language ID="en-us" /
    /Product
    Product ID="VisioPro2019Volume"
      Language ID="en-us" /
    /Product
    Product ID="ProjectPro2019Volume"
      Language ID="en-us" /
    /Product
  /Add

  !--  RemoveMSI All="True" / --
  !--  Display Level="None" AcceptEULA="TRUE" /  --
  !--  Property Name="AUTOACTIVATE" Value="1" /  --
/Configuration

**Comment by alexverschoor** [comment] 2018-10-30 14:13
Proofing XML:

Configuration
  Add OfficeClientEdition="64" Channel="PerpetualVL2019"
	Product ID="ProofingTools"
        Language ID="nl-nl" /
    /Product
  /Add

  !--  RemoveMSI All="True" / --
  !--  Display Level="None" AcceptEULA="TRUE" /  --
  !--  Property Name="AUTOACTIVATE" Value="1" /  --
/Configuration

**Comment by DHB-MSFT** [comment] 2018-10-30 19:28
@alexverschoor -- the product team was able to reproduce the problem and it seems to be a bug. They're in the process of investigating further. Thanks for bringing this to our attention.

**Comment by alexverschoor** [comment] 2018-10-30 19:46
Thank you for the update. When a solution is found, it will be posted here?

**Comment by DHB-MSFT** [comment] 2018-10-30 19:50
Yes, we'll let you know when there's a resolution/fix.  Thanks again.

**Comment by DHB-MSFT** [comment] 2018-11-01 18:12
For now I'm going to close this issue. When we have a resolution, I'll re-open the issue and respond. Thanks.

**Comment by DHB-MSFT** [comment] 2018-11-12 19:35
@alexverschoor -- Please download and use the latest version of the Office Deployment Tool here:
https://www.microsoft.com/en-us/download/details.aspx?id=49117

Version 16.0.11107.33602 resolves an issue which may have prevented installation of Proofing Tools or Language Packs.

**Comment by alexverschoor** [comment] 2018-11-12 20:17
Perfect, I'll try and let you know the outcome (just to be sure, I'll
reinstall the current Office with the new ODT).

**Comment by alexverschoor** [comment] 2018-11-13 18:01
1. Removed all products first
2. Rebooted
3. Installed VL Office 2019
4. trying to install Dutch Proofing tool

Still got errors:

Download/configure Office Professional Plus 2019 with the following
configuration:

<Configuration>
  <Add OfficeClientEdition="64" Channel="PerpetualVL2019">
    <Product ID="ProPlus2019Volume">
      <Language ID="en-us" />
    </Product>
  </Add>
  
  
  
</Configuration>

After download/configure Dutch Proofing tools with the following
configuration:

<Configuration>
  <Add OfficeClientEdition="64" Channel="PerpetualVL2019">
      <Product ID="ProofingTools">
        <Language ID="nl-nl" />
      </Product>
  </Add>
   <Display Level="Full" AcceptEULA="TRUE" />
</Configuration>

I receive this error:

"System Restart Required

Sorry, we ran into a problem. Please try again after restarting your
computer.

Go online for additional help
Error Code: 30182-39 (2)"

**Comment by DHB-MSFT** [comment] 2018-11-13 18:16
@alexverschoor -- thanks for the info. I've sent it on to the PM to investigate.

**Comment by msft-bcorob** [comment] 2018-11-13 23:12
Hi @alexverschoor, the error that you received indicates there was a problem in the file transport.  This could indicate network connectivity problems, a proxy misconfiguration, interference from an aggressive anti-virus program, or something else specific to your device or configuration.  It does not appear to be an issue with the ODT itself or an intentional block regarding proofing tools.

Since we're not able to reproduce the problem that you're experiencing, the next step would be to contact Support for further assistance.  They'll be best suited to help collect the necessary information and investigate further to resolve.

**Comment by alexverschoor** [comment] 2018-11-14 20:57
Thanks, there was an error in my config file. Changed it and now everything
works fine.

This is my config file:

<Configuration> <Add SourcePath="" OfficeClientEdition="64"
Channel="PerpetualVL2019">
<Product ID="ProPlus2019Volume" PIDKEY="#####-#####-#####-#####-#####" >
<Language ID="en-us" />
</Product> <Product ID="ProofingTools">
<Language ID="nl-nl" />
</Product>
</Add>
<RemoveMSI All="True" />
<Display Level="None" AcceptEULA="TRUE" />
</Configuration>

**Comment by DHB-MSFT** [comment] 2018-11-14 22:09
@alexverschoor  -- Glad you got it working. What turned out to be the error in your config file?

**Comment by alexverschoor** [comment] 2018-11-15 13:54
the first ADD of the project ID was not "closed" with a </Product>...

**Closed** 2018-11-15 16:43 UTC
