### ISSUE TITLE
OneNote for Windows 10 & Sharepoint Server

### ISSUE THREAD

**Issue by jonasnilsson86** [MicrosoftDocs/OfficeDocs-DeployOffice#449] opened 2019-09-17 18:00 UTC
Hi, 
I am having a hard time understanding the text "...Instead, OneNote for Windows 10 notebooks must be stored in the cloud. For example, in OneDrive for Business or SharePoint Online. SharePoint Server is also supported".

If OneNote for Windows 10 Notebooks must be stored in the cloud, how can they be stored on Sharepoint Server? Have you updated the functionality to include Sharepoint Server and not revised the rest of the text before stating that Sharepoint Server is supported? If Sharepoint Server is supported, are there any limitations to be aware of?

**Comment by DHB-MSFT** [comment] 2019-09-17 18:20
Closing. Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/450

**Closed by DHB-MSFT** 2019-09-17 18:20 UTC
