### ISSUE TITLE
"Learn More. Some connected experiences aren't available" warning EVERY SINGLE PAGE of OneNote Mac

### ISSUE THREAD

**Issue by ellenble** [MicrosoftDocs/OfficeDocs-DeployOffice#491] opened 2019-11-14 05:03 UTC
Please turn it off or make it pop up JUST ONCE or as a notification, NOT at the top of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef4debee-6a1e-53c7-7bec-2dbd208f4f2d
* Version Independent ID: b93ad6a2-0976-6f5f-7aae-1756079bdc1d
* Content: [Use policy settings to manage privacy controls for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/privacy/manage-privacy-controls)
* Content Source: [DeployOffice/privacy/manage-privacy-controls.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/manage-privacy-controls.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by ItzLevvie** [comment] 2019-11-14 09:32
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/486

**Closed** 2019-11-14 17:10 UTC
