### ISSUE TITLE
"Learn More. Some connected experiences aren't available" warning EVERY SINGLE PAGE of OneNote Mac

### ISSUE THREAD

**Issue by ellenble** [MicrosoftDocs/OfficeDocs-DeployOffice#489] opened 2019-11-14 05:01 UTC
Please turn it off or make it pop up JUST ONCE or as a notification, NOT at the top of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9f215c4-d995-2d6c-0693-bca19f66fe2f
* Version Independent ID: a9aa816b-f30d-3bbe-8fdc-204777b25dfe
* Content: [Connected experiences in Office](https://docs.microsoft.com/en-us/deployoffice/privacy/connected-experiences#connected-experiences-that-download-online-content)
* Content Source: [DeployOffice/privacy/connected-experiences.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/connected-experiences.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by ItzLevvie** [comment] 2019-11-14 09:32
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/486

**Closed** 2019-11-14 17:10 UTC

**Comment by ellenble** [comment] 2020-01-22 18:33
This exact error has resurfaced again. Please fix it

**Comment by DHB-MSFT** [comment] 2020-01-22 18:37
@ellenble -- Thanks for bringing this to our attention. We're letting the OneNote for Mac team know.

**Comment by DHB-MSFT** [comment] 2020-01-22 19:48
@ellenble -- what version of OneNote for Mac are you using? Can you update to 16.33 and see if the problem still exists?  Thanks.
