### ISSUE TITLE
"Learn More. Some connected experiences aren't available" warning EVERY SINGLE PAGE of OneNote Mac

### ISSUE THREAD

**Issue by ellenble** [MicrosoftDocs/OfficeDocs-DeployOffice#490] opened 2019-11-14 05:02 UTC
Please turn it off or make it pop up JUST ONCE or as a notification, NOT at the top of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bb3be5e-7f9c-7743-7594-2253bda3ced7
* Version Independent ID: 88f4baa2-dfcf-1843-ebe1-eeaec0fb604a
* Content: [Overview of privacy controls for Office 365 ProPlus](https://docs.microsoft.com/en-us/deployoffice/privacy/overview-privacy-controls)
* Content Source: [DeployOffice/privacy/overview-privacy-controls.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/overview-privacy-controls.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by ItzLevvie** [comment] 2019-11-14 09:32
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/486

**Closed** 2019-11-14 17:10 UTC
