### ISSUE TITLE
"Learn More. Some connected experiences aren't available" warning EVERY SINGLE PAGE of OneNote Mac

### ISSUE THREAD

**Issue by ellenble** [MicrosoftDocs/OfficeDocs-DeployOffice#538] opened 2020-01-22 18:34 UTC
Please turn it off or make it pop up JUST ONCE or as a notification, NOT at the top of the page.

**Comment by DHB-MSFT** [comment] 2020-01-22 18:46
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/489 and https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/485.

**Closed by DHB-MSFT** 2020-01-22 18:46 UTC
