### ISSUE TITLE
"Learn More. Some connected experiences aren't available" warning EVERY SINGLE PAGE of OneNote Mac

### ISSUE THREAD

**Issue by ellenble** [MicrosoftDocs/OfficeDocs-DeployOffice#488] opened 2019-11-14 05:01 UTC
Please turn it off or make it pop up JUST ONCE or as a notification, NOT at the top of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 144e9c53-1af0-12f0-c083-7775acdc791e
* Version Independent ID: 147f8437-1e9b-1f17-6a20-43904596003b
* Content: [Essential services for Office](https://docs.microsoft.com/en-us/deployoffice/privacy/essential-services)
* Content Source: [DeployOffice/privacy/essential-services.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/essential-services.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by ItzLevvie** [comment] 2019-11-14 09:33
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/486

**Closed** 2019-11-14 17:10 UTC
