### ISSUE TITLE
Proofing tools

### ISSUE THREAD

**Issue by dimmkiss** [MicrosoftDocs/OfficeDocs-DeployOffice#172] opened 2018-11-02 14:04 UTC
I have error "this product can't be installed on the selected update channel" if I try to install any Proofing Tools, like metioned in example. Tryed many PC's, joined to domain or not, in different network providers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626ac155-c2df-20a5-a23f-14921c0c72ae
* Version Independent ID: 63a9307c-d246-bd15-9a2b-178b8a49580b
* Content: [Deploy Office 2019 (for IT Pros)](https://docs.microsoft.com/en-us/deployoffice/office2019/deploy)
* Content Source: [DeployOffice/office2019/deploy.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/office2019/deploy.md)
* Product: **office-perpetual-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by DHB-MSFT** [comment] 2018-11-02 15:06
@dimmkiss -- the product team is aware of this problem and is investigating. We'll provide more info when it's available.  Thanks.

**Comment by dimmkiss** [comment] 2018-11-02 15:15
Thanks.

**Comment by neslekkim** [comment] 2018-11-06 08:51
Same problem here also. How do we get notified when this works?

**Comment by DHB-MSFT** [comment] 2018-11-06 16:16
I'll respond back here. Thanks.

**Comment by zhiqing1993** [comment] 2018-11-07 00:33
I'm running into the same error when trying to install ProPlus2019Volume only using build 16.0.10337.20021. This is what my config.xml looks like:

<Configuration>
  <Add SourcePath="C:\OfficeBuild" OfficeClientEdition="64" Channel="PerpetualVL2019" >
    <Product ID="ProPlus2019Volume" PIDKEY="XXXXX-XXXXX-XXXXX-XXXXX-XXXXX">
      <Language ID="en-us" />      
    </Product>    
  </Add>
  <Updates Enabled="FALSE"/>
  <Display Level="Full" AcceptEULA="TRUE" />
  <Property Name="AUTOACTIVATE" Value="1" />
  <Logging Level="Standard" Path="c:\Temp" />
</Configuration>

Could this share the same root cause with #172?

**Comment by zhiqing1993** [comment] 2018-11-07 00:34
<Configuration>
  <Add SourcePath="C:\OfficeBuild" OfficeClientEdition="64" Channel="PerpetualVL2019" >
    <Product ID="ProPlus2019Volume" PIDKEY="XXXXX-XXXXX-XXXXX-XXXXX-XXXXX">
      <Language ID="en-us" />      
    </Product>    
  </Add>
  <Property Name="AUTOACTIVATE" Value="1" />
</Configuration>

**Comment by DHB-MSFT** [comment] 2018-11-07 00:36
@zhiqing1993 -- yes, it's likely it's the same root cause. Product team is investigating the overall problem.

**Comment by zhiqing1993** [comment] 2018-11-07 01:58
I've figured out what my problem was: I wasn't using the official ODT setup.exe tool, instead I was using the setup.exe from the build. With the latest ODT, I no longer run into this error. Hope that helps.

**Comment by neslekkim** [comment] 2018-11-07 06:18
What is the latest?, I downloaded it yesterday from MPN site.

**Comment by neslekkim** [comment] 2018-11-07 21:34
That's great, to bad it wasn't linked to from MPN site. This tool is very new to me :)
Wish it was better documented, to see what options I can use. I had to google to find the language codes for instance.

**Comment by DHB-MSFT** [comment] 2018-11-07 23:33
@neslekkim -- after the table of Office 2019 relevant settings for the xml file, there is a link to [Configuration options for the Office Deployment Tool](https://docs.microsoft.com/en-us/deployoffice/configuration-options-for-the-office-2016-deployment-tool). It might be easy to overlook that link after the long table, so I'll put it in a callout so it stands out more. Thanks.

**Comment by neslekkim** [comment] 2018-11-08 06:39
ah, great!, exactly what I needed. I see now I was a bit fast, I didn't see the green big box :)

**Comment by neslekkim** [comment] 2018-11-08 22:34
Ah, great, I was really wondering how I could miss that box :)

**Comment by Bebbub** [comment] 2018-11-10 03:04
Using the Office Customization Tool, I can't add German proofing tools, although in the sample configuration.xml file provided on this page it looks possible:
   <Product ID="ProofingTools">
        <Language ID="de-de" />
   </Product>
I can only add the full UI package, what I don't need.

**Comment by kirezafirov** [comment] 2018-11-12 10:02
When the bug for proofing tools in the latest ODT will be fixed. I've get the same error "this product can't be installed on the selected update channel".

**Comment by msft-bcorob** [comment] 2018-11-12 19:31
Please download and use the latest version of the ODT here:
https://www.microsoft.com/en-us/download/details.aspx?id=49117

Version 16.0.11107.33602 resolves an issue which may have prevented installation of Proofing Tools or Language Packs.

**Comment by DHB-MSFT** [comment] 2018-11-13 21:15
@Bebbub -- The Office Customization Tool doesn't currently support adding proofing tools, but the product team is looking into adding that functionality.  The UI is a bit confusing because it looks like you can add proofing tools. To actually add proofing tools, like in the sample xml in the article, make all your other selections in the Office Customization Tool and export the xml file. Then manually add the proofing tool info into that xml, like shown in the sample xml in the article. Hope that helps.

**Closed** 2018-11-14 18:50 UTC

**Comment by gexqin** [comment] 2018-11-27 02:04
I have not understand why when I click the links try to download files it show me like below. It is not office 2019 it is still 2016 16.0.9126.2315.

Version:
2016
File Name:
officedeploymenttool_11107-33602.exe
Date Published:
11/12/2018
File Size:
2.7 MB

**Comment by gexqin** [comment] 2018-11-27 02:08
One more comments. For my understanding office v 15.x is 2013 and v 16.x is 2016 then 2019 should be v 17.x right?

**Comment by DHB-MSFT** [comment] 2018-11-27 21:04
@gexqin --Office 2019 also uses the 16.x version numbering. The product team did this to make certain update/upgrade scenarios less complicated.  And even though the ODT download page says "2016" and the ODT s version 16.0.####.####, the latest ODT can also be used with Office 2019 deployments.

**Comment by Pedromanuelsilva** [comment] 2019-01-07 11:53
Any ETA on when we can install proofing tools on Office 2019 VL without installing the full language package?

**Comment by Bebbub** [comment] 2019-01-07 13:21
The proofing tools issue was already fixed on 11/12/2018, when the version 16.0.11107.33602 of ODT was released. Everything works as it should since then.
