### ISSUE TITLE
Identity theft and fraud

### ISSUE THREAD

**Issue by crs2020** [MicrosoftDocs/OfficeDocs-DeployOffice#496] opened 2019-11-24 20:41 UTC
this is Identity theft and fraud. I did not authorize any contact with this product or software. Delete any and all contact use connection with me personally. I don't use your product I'm not aware of this I did not authorize any use or connection to my personal self with your software. Please contact me at 480-506-8408 and confirm deletion separation cease-and-desist any and all connections with me personally.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9f215c4-d995-2d6c-0693-bca19f66fe2f
* Version Independent ID: a9aa816b-f30d-3bbe-8fdc-204777b25dfe
* Content: [Connected experiences in Office](https://docs.microsoft.com/en-us/deployoffice/privacy/connected-experiences#connected-experiences-that-analyze-your-content)
* Content Source: [DeployOffice/privacy/connected-experiences.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/connected-experiences.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by ItzLevvie** [comment] 2019-11-25 00:48
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/495

**Closed** 2019-11-25 17:11 UTC
