### ISSUE TITLE
"Learn More. Some connected experiences aren't available" warning EVERY SINGLE PAGE of OneNote Mac

### ISSUE THREAD

**Issue by ellenble** [MicrosoftDocs/OfficeDocs-DeployOffice#492] opened 2019-11-14 05:04 UTC
Please turn it off or make it pop up JUST ONCE or as a notification, NOT at the top of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d22aec53-c328-ee44-0b01-475d6ee3f940
* Version Independent ID: 2b39a702-7f42-9b63-d27b-af4806646770
* Content: [Overview of optional connected experiences in Office](https://docs.microsoft.com/en-us/deployoffice/privacy/optional-connected-experiences)
* Content Source: [DeployOffice/privacy/optional-connected-experiences.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/optional-connected-experiences.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @DHB-MSFT
* Microsoft Alias: **danbrown**

**Comment by ItzLevvie** [comment] 2019-11-14 09:32
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/486

**Closed** 2019-11-14 17:10 UTC
