### ISSUE TITLE
"Learn More. Some connected experiences aren't available" warning EVERY SINGLE PAGE of OneNote Mac

### ISSUE THREAD

**Issue by ellenble** [MicrosoftDocs/OfficeDocs-DeployOffice#486] opened 2019-11-14 04:58 UTC
Please turn it off or make it pop up JUST ONCE or as a notification, NOT at the top of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea7bb8bf-5d11-87cb-a880-2edc355dca56
* Version Independent ID: fa4bfa40-42bf-bf0d-413d-d67e8ae826b9
* Content: [Use preferences to manage privacy controls for Office for Mac](https://docs.microsoft.com/en-us/deployoffice/privacy/mac-privacy-preferences)
* Content Source: [DeployOffice/privacy/mac-privacy-preferences.md](https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/blob/live/DeployOffice/privacy/mac-privacy-preferences.md)
* Service: **o365-proplus-itpro**
* GitHub Login: @pbowden-msft
* Microsoft Alias: **danbrown**

**Comment by ItzLevvie** [comment] 2019-11-14 09:39
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-DeployOffice/issues/485

**Closed** 2019-11-14 17:10 UTC
